### ISSUE TITLE
Please release 3.0.1

### ISSUE THREAD

**Issue by jcoyne** [weppos/breadcrumbs_on_rails#102]
I'd like to see 3.0.1 released, so that I can bump the version dependency in my gem that uses breadcrumbs_on_rails.  Thanks. :shipit:

**Comment by weppos** [comment]
I'm on a business trip this week, hence I can't guarantee I will be able to make it happen. I'll do it ASAP.

**Comment by jcoyne** [comment]
How's this week looking? 😉

**Comment by chardos** [comment]
+1

**Comment by weppos** [comment]
https://rubygems.org/gems/breadcrumbs_on_rails/versions/3.0.1

**Comment by weppos** [comment]
I'd appreciate if someone can confirm it fixes #77, as I can't test in Rails 5.0 right now.

**Comment by jcoyne** [comment]
👏 Thanks @weppos

**Comment by weppos** [comment]
Thanks for your help @jcoyne
