### ISSUE TITLE
undefined method `helper' for ActionController::API:Class

### ISSUE THREAD

**Issue by afuno** [weppos/breadcrumbs_on_rails#103]
Rails 5.0.0.
When the application starts I get error:

> /lib/breadcrumbs_on_rails/action_controller.rb:16:in `block in <module:ActionController>': undefined method`helper' for ActionController::API:Class (NoMethodError)

I did not understand, where is the bug fixed https://github.com/weppos/breadcrumbs_on_rails/pull/77 ?

**Comment by civrot** [comment]
I am seeing the same thing.

**Comment by weppos** [comment]
The new version has not been released yet.

**Comment by afuno** [comment]
@weppos It's really critical bug. I'm asking you to fix it as soon as possible.

**Comment by weppos** [comment]
It's fixed, and will be published as soon as I can. If you feel it's crytical for you, use Bundler to point to the repo.

**Comment by Arunk1390** [comment]
@weppos When can we expect the fix for this issue? Before September?

**Comment by weppos** [comment]
Closed by #99
