### ISSUE TITLE
breadcrumbs_on_rails with rspec v3

### ISSUE THREAD

**Issue by lethunder** [weppos/breadcrumbs_on_rails#106]
Hello evryone,
i'm trying to run some test with rspec but i have an error "undefined method `add_breadcrumb' for HistoriesController:Class (NoMethodError) ...."
How can i require breadcrumbs_on_rails in my test. I've tried to insert in my spec_helper.rb
require 'breadcrumbs_on_rails'
BUT STILL NOT WORKING
Please help

**Comment by weppos** [comment]
Please use https://stackoverflow.com/ for support.
