### ISSUE TITLE
should we update bootstrap-default nav?

### ISSUE THREAD

**Issue by krtschmr** [weppos/breadcrumbs_on_rails#107]
https://github.com/krtschmr/breadcrumbs_on_rails/commit/aa63db1db8fcb60cd2345c0b105b2c78db97ec03

bootstrap required the class-name, but there is no chance to hijack the classname into for those elements. should we provide an option for that?

**Comment by ChristopherJMiller** [comment]
I personally would find that useful. With lacking this option, my current implementation is janky and doesn't fully utilize bootstrap's components.

**Comment by weppos** [comment]
You can use a custom builder.
