### ISSUE TITLE
Put dependencies on the right place on gemspec

### ISSUE THREAD

**Issue by michelboaventura** [weppos/breadcrumbs_on_rails#109]
Hi,

I'm having trouble with this gem and rails 3.x. The issue is that newer versions of this gems aren't compatible with rails 3.x but this is not defined on gemspec, since rails is only a ``development`` dependency. Because of that if I do a ``bundle update`` on a rails 3.x app it will update the gem to 3.0.1 and broke the app. Shouldn't you put rails > 4 as a "regular" dependency?

Thanks!

**Comment by raphaottoni** [comment]
Just a +1 on this issue.

I had the same problem.

**Comment by weppos** [comment]
That's a valid argument. I will consider that.

**Comment by michelboaventura** [comment]
Thank you @weppos!
