### ISSUE TITLE
:title in options do not work

### ISSUE THREAD

**Issue by devyani9999** [weppos/breadcrumbs_on_rails#113]
`add_breadcrumb "index", index_path, :title => "Back to the Index"` does not change the title of 'index' to 'Back to Index'. I also tried   `add_breadcrumb "index", index_path, {:title => "Back to the Index}"` but it doesn't work either. 
Is the title in options discontinued?

**Comment by weppos** [comment]
This works if you use the controller instance method. If you use the class method, you need to wrap it into `:options`.

See https://github.com/weppos/breadcrumbs_on_rails/blob/master/lib/breadcrumbs_on_rails/action_controller.rb#L74
