### ISSUE TITLE
Dynamic switching languages only changes last element

### ISSUE THREAD

**Issue by PragmaticEd** [weppos/breadcrumbs_on_rails#115]
If using provided example:

```ruby
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = (params[:locale] || I18n.locale) # simplified for example
  end
end

class Admin::ApplicationController < ApplicationController
  add_breadcrumb I18n.t("breadcrumbs.admin"), admin_path
end

class Admin::UsersController < Admin::ApplicationController
  add_breadcrumb I18n.t("breadcrumbs.admin_users"), admin_users_path
end
```

And we go to `/admin/users?locale=en`

it loads perfectly: 
`Admin / Users`

But if we switch language and refresh the page: `/admin/users?locale=lv`

I get `Admin / Lietotāji`, when it should be `Administrācija / Lietotāji`, meaning, it only translates the last item.

To get the all breadcrumbs to update, u have to go to first link, admin_path in this case, and then click to the last one, admin_users_path, in this example. 

Any ideas how to fix this?

**Comment by weppos** [comment]
You need to use the instance-level `add_breadcrumb`, otherwise the value is cached at class level.

I encourage you to use https://stackoverflow.com/ for support.

**Comment by PragmaticEd** [comment]
So, basically, repeat ur self in each action of each controller..

**Comment by weppos** [comment]
Use a before action.

**Comment by NSNJRGL** [comment]
Is it solved? How to solve it?
