### ISSUE TITLE
Breadcrumbs don't work if controller action is private

### ISSUE THREAD

**Issue by SaladFork** [weppos/breadcrumbs_on_rails#116]
```rb
class MyController < ApplicationController
  private
  def my_action
    add_breadcrumb 'Test'
  end
end
```

The breadcrumbs appear if `private` is commented out but do not appear if left in. The Rails routing and the rest of the UI works correctly in either case.

**Comment by weppos** [comment]
Controller actions are not supposed to be private.
http://guides.rubyonrails.org/action_controller_overview.html#methods-and-actions

> Only public methods are callable as actions. It is a best practice to lower the visibility of methods (with  private or protected) which are not intended to be actions, like auxiliary methods or filters.

**Comment by SaladFork** [comment]
Sorry for the noise, thanks!
