### ISSUE TITLE
Can you add css class to this?

### ISSUE THREAD

**Issue by spacerobotTR** [weppos/breadcrumbs_on_rails#120]
I haven't been able to get it to work so far. Is there a certain way you need to do it?

**Comment by weppos** [comment]
https://github.com/weppos/breadcrumbs_on_rails/blob/d389feac27b507e857462127118da46447be8136/lib/breadcrumbs_on_rails/action_controller.rb#L27

`options` accepts any option you would pass to a `link_to` helper. For more sophisticated styles you need a custom renderer.
