### ISSUE TITLE
Is there a way to pass args to target_path?

### ISSUE THREAD

**Issue by MrSkinny** [weppos/breadcrumbs_on_rails#123]
In example:

```
add_breadcrumb "home", :root_path
```

Is there a way to call `root_path` with arguments, like `root_path(foo: 'bar')` to produce `/?foo=bar`

One of my gallery controllers is expecting an `item_type` param to filter between different items in the gallery.

**Comment by weppos** [comment]
Yes, you can use a `before_action` and call inside the instance-level `add_breadcrumb`. At that point the second argument doesn't have to be a symbol but it can be a method call.
