### ISSUE TITLE
Separator not displayed

### ISSUE THREAD

**Issue by galievruslan** [weppos/breadcrumbs_on_rails#126]
Hello
My stack: Rails 5, Bootstap 3, breadcrumbs_on_rails 3.0.1, slim

My code is:

layouts / admin
```
= render_breadcrumbs :separator => "/"
```
users_controller.rb
```
add_breadcrumb I18n.t(:users), :users_path
...
def edit
   add_breadcrumb I18n.t(:edit), edit_user_path (@user)
end
```

The output is such HTML
```
<ol class="breadcrumb">
     <li><a href="/members">Users</a></li>
   <li class="active">Edit</li>
</ ol>
```
Why is the separator not displayed? I already tried Custom Builder does not help. Tell me please.

**Comment by loyaruarutoitsu** [comment]
@galievruslan Please check if you are using the gem 'twitter-bootstrap-rails' as well. I have the same issue but it seems it is due to a similar gem using the same method named "render_breadcrumbs" resulting in an error.

**Comment by weppos** [comment]
Closing as support should go to https://stackoverflow.com/
