### ISSUE TITLE
add_breadcrumb is showing the text of the breadcrumb but they are not links

### ISSUE THREAD

**Issue by Keith-O-Brien** [weppos/breadcrumbs_on_rails#127]
I've set the gem up in my project, bundled etc, added `render_breadcrumbs` in the view and added `add_breadcrumb "home", :root_path` to my controller. 
The text is displaying but they are not links and are not clickeable. Is there some issue with the gem recently or is the issue on my machine?

Using rails '4.2.10', ruby '2.5.1'

**Comment by KodyKendall** [comment]
Ok.. I'm having the same issue. Can I get some feedback on this?
