### ISSUE TITLE
Use schema.org microdata with breadcrumbs_on_rails

### ISSUE THREAD

**Issue by dim321** [weppos/breadcrumbs_on_rails#131]
Hello !
Could you please tell me, how can I use microdata https://schema.org/BreadcrumbList with this awesome gem ? 
Thank you !

**Comment by weppos** [comment]
You can [define a custom Builder](https://github.com/weppos/breadcrumbs_on_rails/blob/5fafea7878bb327d5a7036b47d9ae9f5a203125c/lib/breadcrumbs_on_rails/breadcrumbs.rb#L72-L100) to personalize the rendering capabilities.

**Comment by richardonrails** [comment]
This seems like it would be a nice built-in option for the gem, given that Google likes this type of structured data for breadcrumbs:
https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by richardonrails** [comment]
On the other hand if you don't think it belongs in the gem, you might consider making it a bit easier to use custom markup. I was looking at a similar gem https://github.com/piotrmurach/loaf#22-breadcrumb_trail and it allow defining arbitrary HTML purely through ERB by passing a block.

**Comment by gowthamgts** [comment]
@richardonrails - issued a PR for this.
