### ISSUE TITLE
Why is this gem explicitly mixed in?

### ISSUE THREAD

**Issue by leehericks** [weppos/breadcrumbs_on_rails#132]
I guess this is a matter of style, but I don't like that this gem mixes into ActionController implicitly.

Why not `include Breadcrumbs` explicitly?

Due to breaking compatibility, I don't expect this behavior to change, but at the same time I'm curious as I'm looking for a good solution and this seems to be the most widely used.

I'm also guessing the `alias add_breadcrumb add_breadcrumb_on_rails` was to avoid breaking changes when improving the API?

Thanks.

**Comment by weppos** [comment]
It is (or was) a very common pattern to initialize on require. It makes it easier for people to get started. Most Rails plugins do it.

**Comment by leehericks** [comment]
Thank you for your reply!
