### ISSUE TITLE
For some reason last breadcrumb is still a link

### ISSUE THREAD

**Issue by tedlin182** [weppos/breadcrumbs_on_rails#14]
It works on other pages, but for this page in particular I am leaving out the breadcrumb to it's parent page, and now it doesn't seem to convert the last breadcrumb (the current page you are on) to just text.

**Comment by borwahs** [comment]
@tedlin182, @weppos 

I know this is a bit old, but I came across a similar problem that might be similar in case future people run into it.

https://github.com/weppos/breadcrumbs_on_rails/issues/29
