### ISSUE TITLE
Missing required keys: [:id]

### ISSUE THREAD

**Issue by LJ-03** [weppos/breadcrumbs_on_rails#140]
Hey there,

I'm trying to add breadcrumbs for my show page, but I get the error:

`No route matches {:action=>"show", :controller=>"projects"}, missing required keys: [:id]`

when trying to access the index page.

my controller:

  ```
add_breadcrumb "home", :root_path
  add_breadcrumb "properties", :projects_path
  add_breadcrumb "show", :project_path

# GET /projects
  # GET /projects.json
  def index 
     add_breadcrumb "properties", projects_path
  end

  
  def show
    @developer = @project.developer
    @description = @project.description
    add_breadcrumb "show", project_path
    #add_breadcrumb "show", projects_path
    #add_breadcrumb "Debt #{@project.id}", project_path(@project.id)
  end
```

I've only set `<%= render breadcrumb %>` from the index view at present, nowhere else. Am I missing something on how to incorporate id's into breadcrumbs? It's not nested resources.

**Comment by weppos** [comment]
This looks like an error with how you pass IDs to routing. Changes are `@project.id` returns a nil value. For more assistance I recommend you use https://stackoverflow.com/
