### ISSUE TITLE
Use custom Builder as default for an application?

### ISSUE THREAD

**Issue by coxandrew** [weppos/breadcrumbs_on_rails#34]
Is there a way to make a custom Builder the default for an app? Not the default for the gem, but just on a specific application?

I'm using the [`BootstrapBreadcrumbsBuilder`](https://gist.github.com/1933884), which is a great option, but using the `:builder` option every time is a little cumbersome:

```
<%= render_breadcrumbs :builder => BootstrapBreadcrumbsBuilder %>
```

I thought I might be able to just rename my class to `SimpleBuilder` to overwrite the default, but that didn't work. Are there any other ways to allow me to just write `render_breadcrumbs` and have it use my Builder?

**Comment by drale2k** [comment]
+1 for this

**Comment by weppos** [comment]
Closing for now. It's possible to define a custom helper which sets the desired default behavior.
