### ISSUE TITLE
Problem with translation 

### ISSUE THREAD

**Issue by jeffersonegenial** [weppos/breadcrumbs_on_rails#61]
I'm using three languages ​​in my application, when changing language sometimes he translates, sometimes not. 

How to solve? 

Since I am using: 
   add_breadcrumb I18n.t ("activerecord.models.account"): accounts_path 
   add_breadcrumb I18n.t (: listing): accounts_path,: only => [: index] 
   add_breadcrumb I18n.t (: new): new_account_path,: only => [: new,: create] 
   add_breadcrumb I18n.t (: editLbl): edit_account_path,: only => [: edit,: update]

**Comment by sasselin** [comment]
+1
Same thing!

**Comment by marcelofraga** [comment]
+1

**Comment by xandrck** [comment]
I have same problem. After refreshing page breadcrumb randomly uses locales.

I solved it this way:

```
before_filter :parent_breadcrumb

private
def parent_breadcrumb
  add_breadcrumb I18n.t ("activerecord.models.account"): accounts_path 
end
```

**Comment by weppos** [comment]
Closing as won't fix. The solution suggested by @xandrck is the best one, as it doesn't depend on the order used to load the various dependencies (including localizations).
