### ISSUE TITLE
Release to Rubygems?

### ISSUE THREAD

**Issue by fredngo** [weppos/breadcrumbs_on_rails#70]
Any chance we could get a release to Rubygems? The last released version, 2.3.0, is from Dec 2012, nearly 2.5 years old…

I know it's more work, thanks in advance for considering it.

**Comment by weppos** [comment]
There are no specific changes, except one, in master.
https://github.com/weppos/breadcrumbs_on_rails/blob/master/CHANGELOG.md

I'll release a bugfix release.

**Comment by fredngo** [comment]
Ah, thank you very much.

**Comment by bjensen** [comment]
So when is the release coming? :-)

**Comment by weppos** [comment]
@bjensen Any specific reason you need a release?

**Comment by runar** [comment]
@weppos I had to point the gem to the master branch to get titles (options) working, so I guess that is one reason for a release?

**Comment by weppos** [comment]
I'll package a new version tomorrow.

**Comment by McRip** [comment]
:+1:

**Comment by weppos** [comment]
Released 2.3.1
