### ISSUE TITLE
Not rendering links in action create

### ISSUE THREAD

**Issue by ffscalco** [weppos/breadcrumbs_on_rails#74]
Hey! ;]

I'm facing a problem with my action create. For example, when I need render action new for some info missing, the link for action create is the same for action index, then the breadcrumb with link to index is not rendering properly. Perhaps change the `link_to_unless_current` to create the path with controller and action instead the path resolve the problem.

It is possible?
Thanks!

**Comment by weppos** [comment]
You can customize the rendering by using a custom builder.
