### ISSUE TITLE
Compatibility with Friendly ID

### ISSUE THREAD

**Issue by wtholt** [weppos/breadcrumbs_on_rails#85]
I'm using this gem and Friendly ID in one of my projects.

    def show
      @section = Section.friendly.find(params[:id])
      add_breadcrumb 'Introduction', section_path(@section)
    end

This doesn't return an active link in the html, just plain text. Is there a workaround for this or am I just doing something wrong?

**Comment by weppos** [comment]
I'm sorry, but I can't provide specific support for other libraries. I suggest to open the question at http://stackoverflow.com/

**Comment by wtholt** [comment]
OK, I just forked your repo to see if I can come up with come capability. If I'm successful, I'll return with a PR.
