### ISSUE TITLE
Add Microdata to Breadcrumbs

### ISSUE THREAD

**Issue by njall** [weppos/breadcrumbs_on_rails#87]
Suggest having an enable-able microdata formatting of breadcrumbs so Google and other search engines can interpret the breadcrumbs in their results display.   
https://developers.google.com/search/docs/data-types/breadcrumbs

**Comment by weppos** [comment]
You can easily accomplish it by creating a custom builder.

**Comment by njall** [comment]
Ah thanks. Do you have any examples/documentation on custom builders?

**Comment by weppos** [comment]
You can find more here:
https://github.com/weppos/breadcrumbs_on_rails/blob/master/lib/breadcrumbs_on_rails/breadcrumbs.rb

Use the `builder` option to specify the builder to use
https://github.com/weppos/breadcrumbs_on_rails/blob/master/lib/breadcrumbs_on_rails/action_controller.rb#L82
