### ISSUE TITLE
undefined method `add_breadcrumb' for HomeController:Class

### ISSUE THREAD

**Issue by jerome-diver** [weppos/breadcrumbs_on_rails#88]
I do follow exactly the readme for install and make running your gem. I add add_breadcrumb to my home default controller, then add a render_breadcrumbs on layout/application.haml view page, and it simple doesn't works like that.
Rails-4.2.3

the error is:
undefined method `add_breadcrumb' for HomeController:Class

Are you sure this gem can run with rails-4 ?

**Comment by weppos** [comment]
Yes, it does.
https://github.com/weppos/breadcrumbs_on_rails/blob/master/Appraisals

Make sure you properly added the gem to your dependencies.

**Comment by jerome-diver** [comment]
@weppos, as i tell you: "i followed exactly the readme for install it". So, i hope you understand that if "i follow exactly the readme for install", i sure make the gem file and i also see that it was installed via bundle install to. So it is definitly not the problem origin.
Anyway... i changed for an other one (breadcumbler) and had the same problem... the problem was certainly because i do execute via a nginx/passenger server instead of use webrick or other... then i had to restart the server. I think you could make the choice to add this crucial information in the readme (it should help for some situation like mine). 
thank you for well read messages and take care about the content of the messages.
