### ISSUE TITLE
Second level not added as a link

### ISSUE THREAD

**Issue by julianonunes** [weppos/breadcrumbs_on_rails#89]
I've placed `add_breadcrumb I18n.t('breadcrumbs.homepage'), :root_path` in the base controller, `add_breadcrumb I18n.t('breadcrumbs.insurance_companies'), :insurance_companies_path` in the child controller (outside any action method) and `add_breadcrumb I18n.t('breadcrumbs.search')` in the index action, however only the root level was created as a hyperlink. Why?

**Comment by weppos** [comment]
Please use  https://stackoverflow.com/ for support
